name: Dependabot automerge
on: pull_request
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Clean and Run Unit Tests
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 6.6.1
          arguments: clean assemble test
  automerge:
    name: Rebase dependabot PRs
    needs: [unit-tests]
    if: ${{github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    runs-on: ubuntu-latest
    steps:
      - name: Rebase Dependabot PR
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.PERSONAL_TOKEN}}
          script: |
            github.pulls.merge({
                owner: context.repo.owner,
                repo: context.payload.repository.name,
                pull_number: context.payload.pull_request.number,
                merge_method: 'rebase'
            });